### ISSUE TITLE
Screen Rotation doesn't follow system settings

### ISSUE THREAD

**Issue by ins2d** [dmitriy-ilchenko/QrAndBarcodeScanner#35] opened 2020-10-06 22:30 UTC
Big up for this great little app!!!

The issue (small but itchy) - UI rotates even when Screen Rotation is locked system-wide. Must either simply follow system setting (better IMO) or have a setting/button for more options in the UI.

OnePlus 6, Oreo 8.1.0

:-*

**Comment by dmitriy-ilchenko** [comment] 2020-10-07 07:29
Duplicate of #34

**Closed by dmitriy-ilchenko** 2020-10-07 07:29 UTC
