### ISSUE TITLE
No app found for this action [Browser]

### ISSUE THREAD

**Issue by Porrumentzio** [dmitriy-ilchenko/QrAndBarcodeScanner#30] opened 2020-09-25 09:30 UTC
After scanning an EAN-13, tap on `Search on the web` or `Open link` and receiving a toast message: `No app found for this action`

Seems that it's searching for a search engine or so but doesn't find it. But both Amazon and eBay work well, so it's not a problem with the browser itself.

- /e/OS 0.11, Android 7.1.2
- Bromite browser

**Comment by dmitriy-ilchenko** [comment] 2020-09-26 09:22
This issue is connected with #19. It seems that Bromite Browser does not support handling intents for web search (with action = Intent.ACTION_WEB_SEARCH). You can use v1.4 of my app to be able to choose a search engine you would like to use for web searches. In that case, the app will send intents containing whole URLs (like 'https://www.google.com/search?q=some_text'), and they should be handled by all browsers.

**Comment by dmitriy-ilchenko** [comment] 2020-10-07 07:37
I am closing this issue because it is actually a duplicate of #19 and it was fixed. Please read [this comment](https://github.com/dmitriy-ilchenko/QrAndBarcodeScanner/issues/19#issuecomment-694212405) for the full explanation.

**Closed by dmitriy-ilchenko** 2020-10-07 07:37 UTC
