### ISSUE TITLE
Make Barcode background white and add button to maximize screen brightness temporarily

### ISSUE THREAD

**Issue by UnlimitedCookies** [dmitriy-ilchenko/QrAndBarcodeScanner#25] opened 2020-09-20 17:26 UTC
So far I am really enjoying this app; thanks for developing it!

I am currently missing these two features:
- Ability to make the barcode background white
- Ability to temporarily increase the brightness of the screen

This  will increase readability for barcode readers.

A button in the upper right corner to increase the brightness to max would be perfect.

![Screenshot_20200920-190157](https://user-images.githubusercontent.com/49200216/93717603-234ab500-fb77-11ea-90b1-644e85e0ef61.png)

**Comment by dmitriy-ilchenko** [comment] 2020-09-20 23:02
Hello. Thank you for your feedback. Hopefully I will implement these features in the next release.

**Comment by dmitriy-ilchenko** [comment] 2020-09-23 08:04
These features were implemented in v1.4. Soon it will be available in app stores. I will leave this issue open for some time so if you are interested you can leave a feedback or report a bug.

**Comment by UnlimitedCookies** [comment] 2020-09-29 15:11
Hey there,
thanks for the quick update to the app!

On my Pixel 2 XL the background of the QR/Barcode is still black, as seen in the screenshot.
![Screenshot_20200929-165121](https://user-images.githubusercontent.com/49200216/94577418-de113c00-0276-11eb-80de-5ae764bfe4fa.png)

**Comment by dmitriy-ilchenko** [comment] 2020-10-07 07:48
Actually I have no idea why this happens. I can't reproduce the bug. Could you please tell me:

- OS version

- Is "Inverse code colors in dark theme" option enabled or not

**Comment by alaincao** [comment] 2020-10-17 21:58
Heylow, same problem here.  
- Android 10 (Fairphone 3)
- Tried with both "Inverse code colors in dark theme" option toggled and not-toggled, same result
- Got the application through F-Droid (up to date as of 2020-10-17)
- **Dark theme activated in the system's settings**
nb: if I select "Same as system" in the settings, I have the issue. OTOH, I *explicitely* select the "Dark" theme, the issue is resolved...  

Love the app, BTW. Thank you!

**Comment by UnlimitedCookies** [comment] 2020-10-17 22:39
Hey. Yep, the toggle doesn't change anything actually.
I hope this video does help somewhat. (And I had to zip it for Githug).
[screen-20201007-122328_2.zip](https://github.com/dmitriy-ilchenko/QrAndBarcodeScanner/files/5396809/screen-20201007-122328_2.zip)

**Comment by dmitriy-ilchenko** [comment] 2020-10-20 14:24
Should be fixed in v1.5

**Closed by dmitriy-ilchenko** 2020-10-20 14:24 UTC

**Comment by UnlimitedCookies** [comment] 2021-01-10 08:46
I am very glad this works properly now!

One minor thing:
Might it be possible to have a small white border around the barcode/QR code so that the reader can properly differentiate the data around the corners?

Thanks!

**Comment by VasilisKos** [comment] 2022-03-20 16:39
Hi. The brightness button on the top right corner, which is supposed to maximize the brightness when viewing a code, is doing nothing at all. At least on Android 11 that I use, on a Nokia 6.2.
